// Generated by CoffeeScript 1.6.3
(function() {
  return Nimbus.Share.get_me(function(me) {
    var player;
    console.log('init myself');
    fill_player(me);
    player = Player.findByAttribute('email', me.email);
    return new Tetris(player);
  });
})();
