// Generated by CoffeeScript 1.6.3
(function() {
  var i, _i;
  Tetris.width = 10;
  Tetris.height = 20;
  Tetris.gravity = 300;
  Tetris.block_pixel = 25;
  Tetris.colors = {
    'X': 'black',
    'b': 'cyan',
    'B': 'blue',
    'O': 'orange',
    'Y': 'yellow',
    'G': 'green',
    'P': '#9370D8',
    'R': 'red'
  };
  Tetris.pieces = [];
  for (i = _i = 0; _i < 4; i = ++_i) {
    Tetris.PIECES[i] = [];
  }
  Tetris.pieces[0][0] = ["    ", "    ", "    ", "    ", "    ", "    ", "    "];
  Tetris.pieces[0][1] = ["    ", "B   ", "  O ", " YY ", " GG ", " P  ", "RR  "];
  Tetris.pieces[0][2] = ["bbbb", "BBB ", "OOO ", " YY ", "GG  ", "PPP ", " RR "];
  Tetris.pieces[0][3] = ["    ", "    ", "    ", "    ", "    ", "    ", "    "];
  Tetris.pieces[1][0] = [" b  ", "    ", "    ", "    ", "    ", "    ", "  R "];
  Tetris.pieces[1][1] = [" b  ", " B  ", "OO  ", " YY ", " G  ", " P  ", " RR "];
  Tetris.pieces[1][2] = [" b  ", " B  ", " O  ", " YY ", " GG ", " PP ", " R  "];
  Tetris.pieces[1][3] = [" b  ", "BB  ", " O  ", "    ", "  G ", " P  ", "    "];
  Tetris.pieces[2][0] = ["    ", "    ", "    ", "    ", "    ", "    ", "    "];
  Tetris.pieces[2][1] = ["    ", "    ", "    ", " YY ", " GG ", "    ", "RR  "];
  Tetris.pieces[2][2] = ["bbbb", "BBB ", "OOO ", " YY ", "GG  ", "PPP ", " RR "];
  Tetris.pieces[2][3] = ["    ", "  B ", "O   ", "    ", "    ", " P  ", "    "];
  Tetris.pieces[3][0] = [" b  ", "    ", "    ", "    ", "    ", "    ", "  R "];
  Tetris.pieces[3][1] = [" b  ", " BB ", " O  ", " YY ", " G  ", " P  ", " RR "];
  Tetris.pieces[3][2] = [" b  ", " B  ", " O  ", " YY ", " GG ", "PP  ", " R  "];
  Tetris.pieces[3][3] = [" b  ", " B  ", " OO ", "    ", "  G ", " P  ", "    "];
  Tetris.board = function(canvas, player) {
    var self;
    self = this;
    return this.context = canvas.getContext('2d');
  };
  Tetris.board.prototype.draw = function() {};
  Tetris.board.prototype.drawPiece = function(piece) {};
  Tetris.board.prototype.checkCollision = function(piece) {};
  Tetris.board.prototype.clear = function() {};
  return Tetris.current = function(num, x, y, rotation) {};
});
